{% set name = "honcho" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/honcho-{{ version }}.tar.gz
  sha256: c5eca0bded4bef6697a23aec0422fd4f6508ea3581979a3485fc4b89357eb2a9

build:
  noarch: python
  entry_points:
    - honcho=honcho.command:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.8
    - colorama

test:
  imports:
    - honcho
  commands:
    - pip check
    - honcho --help
  requires:
    - pip

about:
  home: https://github.com/nickstenning/honcho
  summary: Python clone of Foreman for managing Procfile-based applications.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
